backend/api/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.v1.urls')),
    path('', include('services.products_module.urls')),
    path("authentication/", include("services.user_module.urls.auth_urls")),
    path("profile/", include("services.user_module.urls.profile_urls")),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns += path('static/', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT})

backend/services/products_module/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Currency(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    symbol = models.CharField(max_length=1, verbose_name='Symbol')
    price = models.FloatField(verbose_name='Price')
    is_default = models.BooleanField(default=False, verbose_name='Default')


    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        if not self.is_default:
            if not Currency.objects.filter(is_default=True).exists():
                self.is_default = True
        else:
            Currency.objects.filter(is_default=True).update(is_default=False)

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        if self.is_default:
            currency = Currency.objects.first()
            if currency:
                currency.is_default=True
                currency.save()


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = models.TextField(max_length=2000, verbose_name='Description')
    price = models.FloatField(verbose_name='Price')
    currency = models.ForeignKey(Currency,
                                 on_delete=models.CASCADE,
                                 verbose_name='Currency',
                                 related_name='products')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Owner', related_name='products')
    in_stock = models.BooleanField(default=True, verbose_name='In Stock')

backend/services/user_module/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models




class User(AbstractUser):
    is_seller = models.BooleanField(default=False, verbose_name='Seller')
    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def save(self, *args, **kwargs):
        from services.products_module.models import Currency
        if not Currency.objects.first():
            Currency.objects.create(title="USD", symbol ="$", price=0)
        super().save(*args, **kwargs)
        UserSettings.objects.get_or_create(user=self, currency=Currency.objects.first())

class UserAddress(models.Model):
    country = models.CharField(max_length=255, verbose_name='Country')
    city = models.CharField(max_length=255, verbose_name='City')
    address = models.CharField(max_length=255, verbose_name='Address')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', related_name='user_address')


class UserSettings(models.Model):
    currency = models.ForeignKey('products_module.Currency',
                                 on_delete=models.CASCADE,
                                 verbose_name='Currency',
                                 related_name='user_settings')
    is_send_push = models.BooleanField(default=True, verbose_name='Send Push')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User', related_name='user_settings')

backend/services/products_module/forms.py
from django import forms
from services.products_module.models import Product, Currency

class UpdateProductForm(forms.ModelForm):
    #currency_id = forms.IntegerField()

    in_stock = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    currency = forms.ModelChoiceField(
        queryset=Currency.objects.all(),
        to_field_name="pk",
        required=True,
        widget=forms.Select(attrs={"class": "form-control"})
    )
    class Meta:
        model = Product
        #fields = ('title', 'description', 'price', 'currency_id', 'in_stock')
        fields = ('title', 'description', 'price', 'in_stock', 'currency')

backend/services/user_module/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()
class RegistrationForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')

class ProfileForm(forms.ModelForm):
    password_old = forms.CharField(required=False)
    password_new = forms.CharField(required=False)
    class Meta:
        fields = ("first_name", "last_name", "username", "password", "password_new", "password_old")

class AuthForm(forms.Form):
    class Meta:
        fields = ("username", "password")

backend/admin/templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auth</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body class="text-center">

<main class="form-signin w-100 m-auto">
  <form method="POST" class="needs-validation" validate="">{% csrf_token %}
    <img class="mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="text" class="form-control" name="username" id="id_username" placeholder="username">
      <label for="id_username">Username</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" name="password" id="id_password" placeholder="Password">
      <label for="id_password">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <a href="{{ SITE_URL }}/authentication/registration/"></a>
    <p class="mt-5 mb-3 text-muted">© 2023</p>
  </form>
</main>





</body>
</html>

backend/admin/templates/base.html
{#{% load staticfiles %}#}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<style>


  .link_product {
     text-decoration: none;
     color: #000000;
  }

</style>
<body>
  <header>
    <div class="px-3 py-2 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use>></svg>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"/></svg>
                Home
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"/></svg>
                Dashboard
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"/></svg>
                Orders
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"/></svg>
                Products
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"/></svg>
                Customers
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-primary text-dark me-2">Login</button>
          <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
      </div>
    </div>
  </header>


{% block content %}
{% endblock %}




</body>
</html>

backend/admin/templates/create_update_product.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <main>
    <div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>{{ subject }}</h2>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-md-6 col-sm-11">
        <form class="needs-validation" novalidate="">
          <div class="row g-3">
            <div class="col-12">
              <label for="id_title" class="form-label">Title</label>
              <input class="form-control" name="title" value="{{ form.data.title }}" id="id_title" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Please enter a valid title.
              </div>
            </div>

            <div class="col-12">
              <label for="id_description" class="form-label">Description</label>
              <textarea class="form-control" placeholder="Leave a comment here" name="description" id="id_description" style="height: 100px">{{ form.data.description }}</textarea>
              <div class="invalid-feedback">
                Please enter a valid description.
              </div>
            </div>

            <div class="col-12">
              <label for="id_price" class="form-label">Price</label>
              <input type="text" class="form-control" value="{{ form.data.price }}" id="id_price" name="price">
              <div class="invalid-feedback">
                Please enter a valid price.
              </div>
            </div>

            <div class="col-12">
                <select class="form-select" id="id_currency" name="currency" aria-label="Floating label select example">
                    {% for currency in currency_list %}
                        <option {% if form.data.currency == currency or not form.data.currency and currency.is_default %} selected {% endif %} value="{{ currency.pk }}">{{ currency.title }}</option>
                    {% endfor %}
                </select>
              <label for="id_currency" class="form-label">Currency</label>
              <div class="invalid-feedback">
                Please enter a valid Currency.
              </div>
            </div>
          </div>>
           <div class="col-12">
                <input class="form-check-input" type="checkbox" id="id_in_stock" name="in_stock">
                <label class="form-check-label" for="id_in_stock">
                Stock
              </label>
           </div>
          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="send_push">
            <label class="form-check-label" for="send_push">Send Push</label>
          </div>

          <button class="w-100 btn btn-primary btn-lg" type="submit">Registration</button>
        </form>
      </div>
     </div>
  </main>
</div>
{% endblock %}

backend/admin/templates/index.html
{% extends "base.html" %}

{% block content %}

<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active" aria-current="true"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>
        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">



    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">
    {% for product in products %}
    <div class="row featurette">
      <div class="col-md-7 {% if product.id|divisibleby:'2' %} order-md-2 {% endif %}">
        <h2 class="featurette-heading">{{ product.title }}</h2>
        <p class="lead">{{ product.description }}</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">
    {% endfor %}

  <nav aria-label="...">
  <ul class="pagination justify-content-center">">
    <li class="page-item disabled">
      <a class="page-link" href="?page={{ page_number|add:-1 }}">Previous</a>
    </li>
    {% for i in pages_count|get_range%}
    <li class="page-item {% if 1 == page_number %} active {% endif %}"><a class="page-link" href="?page{{ i }}">{{ i }}</a></li>
    {% endfor %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">2</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_number|add:1 }}">Next</a>
    </li>
  </ul>
  </nav>
    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

{% endblock %}

backend/admin/templates/my_products.html
{% extends "base.html" %}

{% block content %}

  <div class="container marketing">
    <a class="btn btn-outline-success justify-content-end" href="{% url 'create_product' %}" role="button">Create</a>
     <hr class="featurette-divider">
     {% for product in products %}
      <a class="link_product" href="{% url 'product' product.id %}">
      <div class="row featurette">
      <div class="col-md-7 {% if product.id|divisibleby:'2' %} order-md-2 {% endif %}">
        <h2 class="featurette-heading">{{ product.title }}</h2>
        <p class="lead">{{ product.description }}</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
      </div>
      </a>
     <hr class="featurette-divider">
     {% endfor %}

  <nav aria-label="...">
  <ul class="pagination justify-content-center">">
    <li class="page-item disabled">
      <a class="page-link" href="?page={{ page_number|add:-1 }}">Previous</a>
    </li>
    {% for i in pages_count|get_range%}
    <li class="page-item {% if 1 == page_number %} active {% endif %}"><a class="page-link" href="?page{{ i }}">{{ i }}</a></li>
    {% endfor %}
    <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">2</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_number|add:1 }}">Next</a>
    </li>
  </ul>
  </nav>
 </div>

{% endblock %}

backend/admin/templates/product.html
{% extends "base.html" %}

{% block content %}

  <div class="container marketing">

    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-7 {% if product.id|divisibleby:'2' %} order-md-2 {% endif %}">
        <h2 class="featurette-heading">{{ product.title }}</h2>
        <p class="lead">{{ product.description }}</p>
        .<p class="lead">{{ product.price }} {{ product.currency.symbol }}</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">
    <div class="row">
    <div class=""><a class="btn btn-outline-primary" href="{% url 'product_update' product.id %}" role="button">Update</a></div>
    <div class=""><a class="btn btn-outline-danger" href="{% url 'product_delete' product.id %}" role="button">Delete</a></div>
    </div>
 </div>

{% endblock %}

backend/admin/templates/profile.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <main>
    <div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>Profile</h2>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-md-6 col-sm-11">
        <h4 class="mb-3">Billing address</h4>
        <form method="POST" class="needs-validation" novalidate="">{% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="id_first_name" class="form-label">First name</label>
              <input type="text" class="form-control" name="first_name" value="{{ form.data.first_name }}" id="id_first_name" placeholder="" required="">
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="id_last_name" class="form-label">Last name</label>
              <input type="text" class="form-control" name="last_name" id="id_last_name" placeholder="" value="{{ form.data.last_name }}" required="">
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="id_email" class="form-label">Email</label>
              <input type="text" class="form-control" name="email" id="id_email" placeholder="" value="{{ form.data.email }}" required="">
              <div class="invalid-feedback">
                Please enter a valid email address.
              </div>
            </div>

            <div class="col-12">
              <label for="id_username" class="form-label">Username</label>
              <input type="text" class="form-control" name="username" value="{{ form.data.username }}" id="id_username">
              <div class="invalid-feedback">
                Please enter a valid username.
              </div>
            </div>

            <div class="col-12">
              <label for="id_password_old" class="form-label">Password Old</label>
              <input type="password" class="form-control" name="password_old" id="id_password_old" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="id_password_new" class="form-label">Password New</label>
              <input type="password" class="form-control" name="password_new" id="id_password_new" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" id="country" required="">
                <option value="">Choose...</option>
                <option>United States</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-5">
              <label for="state" class="form-label">State</label>
              <select class="form-select" id="state" required="">
                <option value="">Choose...</option>
                <option>California</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>
              <div class="col-md-2">
                <label for="currency" class="form-label">currency</label>
                <select class="form-select" id="currency" required="">
                  <option value="">Choose...</option>
                  <option>S</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid currency.
                </div>
              </div>
          </div>>
          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="send_push">
            <label class="form-check-label" for="send_push">Send Push</label>
          </div>

          <button class="w-100 btn btn-primary btn-lg" type="submit">Save</button>
        </form>
      </div>
    </div>
  </main>
</div>
{% endblock %}

backend/admin/templates/registration.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container">
  <main>
    <div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="{% static 'image.jpeg' %}" alt="" width="72" height="57">
      <h2>Registration</h2>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-md-6">
        <form method="POST" class="needs-validation" novalidate="">{% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="id_first_name" class="form-label">First name</label>
              <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="id_last_name" class="form-label">Last name</label>
              <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="id_email" class="form-label">Email</label>
              <input type="email" class="form-control" id="id_email" name="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="id_username" class="form-label">Username</label>
              <input type="text" class="form-control" id="id_username" name="username">
              <div class="invalid-feedback">
                Valid username is required.
              </div>
            </div>

            <div class="col-12">
              <label for="id_password" class="form-label">Password</label>
              <input type="password" class="form-control" id="id_password" name="password" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a password.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" required="">
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>


            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" id="country" required="">
                <option value="">Choose...</option>
                <option>United States</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-5">
              <label for="state" class="form-label">State</label>
              <select class="form-select" id="state" required="">
                <option value="">Choose...</option>
                <option>California</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>


            <div class="col-md-2">
              <label for="currency" class="form-label">Currency</label>
              <select class="form-select" id="currency" required="">
                <option value="">Choose...</option>
                <option>$</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid currency.
              </div>
            </div>
          </div>>


          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="send_push" name="send_push">
            <label class="form-check-label" for="send_push">Send Push</label>
          </div>

          <button class="w-100 btn btn-primary btn-lg" type="submit">Registration</button>
         </form>
      </div>
    </div>
  </main>
</div>
{% endblock %}